### ISSUE TITLE
Eigen & STEM4U package are missing in the upp file

### ISSUE THREAD

**Issue by Xemuth** [anboto/Surface#1]
Hello, 

On fresh Upp install, Surface Demo fetched  from UppHub is not compilable since it miss STEM4U & Eigen & Function4U. 
May it should be added to necessary package of Surface package so it get downloaded when fetching it from UppHub. 

Best regard

**Comment by izabala123** [comment]
Hi Xemuth

You are right. Now the package structure is fixed, and Surface test is included in unitest to test it in the future.
Thank you!!

Best regards
Iñaki

**Comment by Xemuth** [comment]
Hello Izabala123, I just tried compiling Surface from scratch today and STEM4U is still missing from Surface dependencies package . Eigen is fetched as intended

**Comment by izabala123** [comment]
Hi Xemuth

Theoretically STEM4U package is not necessary if it is already included in your system, as only .h files are included.
However if not, this will cause an error. 
Thank you!! I have included STEM4U package into Surface.

Iñaki

**Comment by izabala123** [comment]
Hi [Xemuth](https://github.com/Xemuth)

Please confirm if this is closed for you.

Iñaki
